name: create_resource_group_azure 

on:
    push:
        paths:
        - '.env'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print a message
      run: |
            echo "This job was triggered manually!"

    - name: p2
      id: dotenv
      uses: ./.github/actions/dotenv-action
    - name : p3
      run: ${{ steps.dotenv.outputs.version }}

    # - name: print2
    #   run: |
    #         echo "${{.env.LOL }}"