name: create_resource_group_azure 

on:
    push:
        paths:
        - '.env'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print a message
      run: |
            echo "This job was triggered manually!"


    - uses: oNaiPs/secrets-to-env-action@v1
      with: 
        secrets: ${{ toJSON(secrets) }}

    - name: l
      run: |
         echo "Value of MY_SECRET1: $LOL"

    # - name: Dotenv Action
    #   uses: falti/dotenv-action@v1.1.4
            

    # - name : p3
    #   run: | 
    #     echo "${{ steps.dotenv.outputs.version }}""

    # - name: print2
    #   run: |
    #         echo "${{.env.LOL }}"